### ISSUE TITLE
Permission denied (missing INTERNET permission?)

### ISSUE THREAD

**Issue by mklimek** [tehmou/rx-android-architecture#21]
``` java
Caused by: rx.exceptions.OnErrorNotImplementedException: Permission denied (missing INTERNET permission?)
            at rx.Observable$32.onError(Observable.java:7255)
            at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:154)
            at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:111)
            at rx.internal.operators.OperatorMap$1.onError(OperatorMap.java:49)
            at rx.internal.operators.OperatorSubscribeOn$1$1$1.onError(OperatorSubscribeOn.java:71)
            at com.tehmou.rxbookapp.data.DataLayer.lambda$getGitHubRepositorySearch$5(DataLayer.java:43)
            at com.tehmou.rxbookapp.data.DataLayer.access$lambda$0(DataLayer.java)
            at com.tehmou.rxbookapp.data.DataLayer$$Lambda$1.call(Unknown Source)
            at rx.Observable.unsafeSubscribe(Observable.java:7428)
```

**Comment by tehmou** [comment]
Thanks for fixing, the permission was obviously needed.
